### ISSUE TITLE
Note ignoring folders

### ISSUE THREAD

**Issue by Saorsa32** [zigholding/obsidian-notechain-plugin#3]

**Comment by Saorsa32** [comment]
I'm also getting an failed to update error when I try to update it.

**Comment by zigholding** [comment]
> I'm also getting an failed to update error when I try to update it.

I update this plugin to 1.1.8 for Obsidian 1.7.7. Will it work by update both obsidian and notechain?

**Comment by Saorsa32** [comment]
It started working again and was able to update. Thanks!
